### ISSUE TITLE
Cannot find package '@react-three/babel-plugin-babel'

### ISSUE THREAD

**Issue by adamistheanswer** [pmndrs/react-three-babel#12]
ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find package '@react-three/babel-plugin-babel' imported from /Users/adamrobinson/Documents/ziggy-frontend/babel-virtual-resolve-base.js
    at new NodeError (/Users/adamrobinson/Documents/ziggy-frontend/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:194:5)
    at packageResolve (/Users/adamrobinson/Documents/ziggy-frontend/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:908:9)
    at moduleResolve (/Users/adamrobinson/Documents/ziggy-frontend/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:937:20)
    at defaultResolve (/Users/adamrobinson/Documents/ziggy-frontend/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:1007:15)
    at resolve (/Users/adamrobinson/Documents/ziggy-frontend/node_modules/@babel/core/lib/vendor/import-meta-resolve.js:1020:12)
    at tryImportMetaResolve (/Users/adamrobinson/Documents/ziggy-frontend/node_modules/@babel/core/lib/config/files/plugins.js:142:45)
    at resolveStandardizedNameForImport (/Users/adamrobinson/Documents/ziggy-frontend/node_modules/@babel/core/lib/config/files/plugins.js:164:19)
    at resolveStandardizedName (/Users/adamrobinson/Documents/ziggy-frontend/node_modules/@babel/core/lib/config/files/plugins.js:173:22)
    at loadPlugin (/Users/adamrobinson/Documents/ziggy-frontend/node_modules/@babel/core/lib/config/files/plugins.js:52:20)
    at loadPlugin.next (<anonymous>)
    at createDescriptor (/Users/adamrobinson/Documents/ziggy-frontend/node_modules/@babel/core/lib/config/config-descriptors.js:140:16)
    at createDescriptor.next (<anonymous>)
    at step (/Users/adamrobinson/Documents/ziggy-frontend/node_modules/gensync/index.js:261:32)
    at evaluateAsync (/Users/adamrobinson/Documents/ziggy-frontend/node_modules/gensync/index.js:291:5)
    at /Users/adamrobinson/Documents/ziggy-frontend/node_modules/gensync/index.js:44:11
    at Array.forEach (<anonymous>)
    at Function.async (/Users/adamrobinson/Documents/ziggy-frontend/node_modules/gensync/index.js:43:15)
    at Function.all (/Users/adamrobinson/Documents/ziggy-frontend/node_modules/gensync/index.js:216:13)
    at Generator.next (<anonymous>)
    at createDescriptors (/Users/adamrobinson/Documents/ziggy-frontend/node_modules/@babel/core/lib/config/config-descriptors.js:102:41)
    at createDescriptors.next (<anonymous>)
    at createPluginDescriptors (/Users/adamrobinson/Documents/ziggy-frontend/node_modules/@babel/core/lib/config/config-descriptors.js:99:17)
    at createPluginDescriptors.next (<anonymous>)
    at /Users/adamrobinson/Documents/ziggy-frontend/node_modules/@babel/core/lib/gensync-utils/functional.js:39:27
    at Generator.next (<anonymous>)
    at mergeChainOpts (/Users/adamrobinson/Documents/ziggy-frontend/node_modules/@babel/core/lib/config/config-chain.js:349:34)
    at mergeChainOpts.next (<anonymous>)
    at chainWalker (/Users/adamrobinson/Documents/ziggy-frontend/node_modules/@babel/core/lib/config/config-chain.js:316:14)
    at chainWalker.next (<anonymous>)
    at loadFileChain (/Users/adamrobinson/Documents/ziggy-frontend/node_modules/@babel/core/lib/config/config-chain.js:191:24)
    at loadFileChain.next (<anonymous>)
    at buildRootChain (/Users/adamrobinson/Documents/ziggy-frontend/node_modules/@babel/core/lib/config/config-chain.js:108:31)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (/Users/adamrobinson/Documents/ziggy-frontend/node_modules/@babel/core/lib/config/partial.js:72:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at loadPartialConfig (/Users/adamrobinson/Documents/ziggy-frontend/node_modules/@babel/core/lib/config/partial.js:115:25)
    at loadPartialConfig.next (<anonymous>)
    at step (/Users/adamrobinson/Documents/ziggy-frontend/node_modules/gensync/index.js:269:25)
    at /Users/adamrobinson/Documents/ziggy-frontend/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Users/adamrobinson/Documents/ziggy-frontend/node_modules/gensync/index.js:223:11)
    at /Users/adamrobinson/Documents/ziggy-frontend/node_modules/gensync/index.js:50:45
    at step (/Users/adamrobinson/Documents/ziggy-frontend/node_modules/gensync/index.js:287:14)
    at /Users/adamrobinson/Documents/ziggy-frontend/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Users/adamrobinson/Documents/ziggy-frontend/node_modules/gensync/index.js:223:11)
    at /Users/adamrobinson/Documents/ziggy-frontend/node_modules/gensync/index.js:189:28
    at /Users/adamrobinson/Documents/ziggy-frontend/node_modules/@babel/core/lib/gensync-utils/async.js:67:7
    at /Users/adamrobinson/Documents/ziggy-frontend/node_modules/gensync/index.js:113:33
    at step (/Users/adamrobinson/Documents/ziggy-frontend/node_modules/gensync/index.js:287:14)
    at /Users/adamrobinson/Documents/ziggy-frontend/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Users/adamrobinson/Documents/ziggy-frontend/node_modules/gensync/index.js:223:11)

webpack 5.89.0 compiled with 1 error in 2854 ms

=== Babel.rc ====

{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-typescript",
    ["@babel/preset-react", { "runtime": "automatic" }]
  ],
  "plugins": [
    ["@react-three/babel"],
    "lodash",
    [
      "module-resolver",
      {
        "root": ["./src"]
      }
    ],
    [
      "babel-plugin-styled-components",
      {
        "pure": true
      }
    ]
  ]
}

**Comment by umar-ahmed** [comment]
Hey, thanks for the bug report


What version of Babel are you using?

I'm wondering if we broke backwards compat somehow

**Comment by umar-ahmed** [comment]
@adamistheanswer I think I figured out the issue. There was a mistake in the readme, in your babel config, you need to prefix the plugin name with `module:` as shown below:

```json
{
  "plugins": ["module:@react-three/babel"]
}
```

**Comment by umar-ahmed** [comment]
I'd also recommend upgrading to the latest release: https://github.com/pmndrs/react-three-babel/releases/tag/v1.0.2, which contains a few fixes

**Comment by umar-ahmed** [comment]
@adamistheanswer I'm going to close this issue since it's been stale for a bit. Please re-open a new issue if you find that the latest release didn't fix this bug
